# IP: 172.10.0.50
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address: {
        address: 0.0.0.0,
        port_value: 6379
      }
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: egress_redis
          prefix_routes:
            catch_all_route:
              cluster: redis_standalone
          settings:
            op_timeout: 5s
            enable_redirection: true
            enable_command_stats: true
  clusters:
  - name: redis_standalone
    connect_timeout: 1s
    type: STRICT_DNS
    lb_policy: MAGLEV
    load_assignment:
      cluster_name: redis_standalone
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: {
                address: 172.10.0.61,
                port_value: 6379
              }

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001